/*
 * generated by Xtext
 */
package org.uqbar.paco.dsl.xtext.saludos.ui.contentassist

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SaludosDSLProposalProvider extends AbstractSaludosDSLProposalProvider {

}
