/*
* generated by Xtext
*/
grammar InternalSaludosDSL;

options {
	superClass=AbstractInternalContentAssistParser;
	
}

@lexer::header {
package org.uqbar.paco.dsl.xtext.saludos.ui.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package org.uqbar.paco.dsl.xtext.saludos.ui.contentassist.antlr.internal; 

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.DFA;
import org.uqbar.paco.dsl.xtext.saludos.services.SaludosDSLGrammarAccess;

}

@parser::members {
 
 	private SaludosDSLGrammarAccess grammarAccess;
 	
    public void setGrammarAccess(SaludosDSLGrammarAccess grammarAccess) {
    	this.grammarAccess = grammarAccess;
    }
    
    @Override
    protected Grammar getGrammar() {
    	return grammarAccess.getGrammar();
    }
    
    @Override
    protected String getValueForTokenName(String tokenName) {
    	return tokenName;
    }

}




// Entry rule entryRuleModel
entryRuleModel 
:
{ before(grammarAccess.getModelRule()); }
	 ruleModel
{ after(grammarAccess.getModelRule()); } 
	 EOF 
;

// Rule Model
ruleModel
    @init {
		int stackSize = keepStackSize();
    }
	:
(
{ before(grammarAccess.getModelAccess().getGroup()); }
(rule__Model__Group__0)
{ after(grammarAccess.getModelAccess().getGroup()); }
)

;
finally {
	restoreStackSize(stackSize);
}



// Entry rule entryRuleSaludo
entryRuleSaludo 
:
{ before(grammarAccess.getSaludoRule()); }
	 ruleSaludo
{ after(grammarAccess.getSaludoRule()); } 
	 EOF 
;

// Rule Saludo
ruleSaludo
    @init {
		int stackSize = keepStackSize();
    }
	:
(
{ before(grammarAccess.getSaludoAccess().getAlternatives()); }
(rule__Saludo__Alternatives)
{ after(grammarAccess.getSaludoAccess().getAlternatives()); }
)

;
finally {
	restoreStackSize(stackSize);
}



// Entry rule entryRuleBienvenida
entryRuleBienvenida 
:
{ before(grammarAccess.getBienvenidaRule()); }
	 ruleBienvenida
{ after(grammarAccess.getBienvenidaRule()); } 
	 EOF 
;

// Rule Bienvenida
ruleBienvenida
    @init {
		int stackSize = keepStackSize();
    }
	:
(
{ before(grammarAccess.getBienvenidaAccess().getGroup()); }
(rule__Bienvenida__Group__0)
{ after(grammarAccess.getBienvenidaAccess().getGroup()); }
)

;
finally {
	restoreStackSize(stackSize);
}



// Entry rule entryRuleDespedida
entryRuleDespedida 
:
{ before(grammarAccess.getDespedidaRule()); }
	 ruleDespedida
{ after(grammarAccess.getDespedidaRule()); } 
	 EOF 
;

// Rule Despedida
ruleDespedida
    @init {
		int stackSize = keepStackSize();
    }
	:
(
{ before(grammarAccess.getDespedidaAccess().getGroup()); }
(rule__Despedida__Group__0)
{ after(grammarAccess.getDespedidaAccess().getGroup()); }
)

;
finally {
	restoreStackSize(stackSize);
}



// Entry rule entryRuleAlguien
entryRuleAlguien 
:
{ before(grammarAccess.getAlguienRule()); }
	 ruleAlguien
{ after(grammarAccess.getAlguienRule()); } 
	 EOF 
;

// Rule Alguien
ruleAlguien
    @init {
		int stackSize = keepStackSize();
    }
	:
(
{ before(grammarAccess.getAlguienAccess().getGroup()); }
(rule__Alguien__Group__0)
{ after(grammarAccess.getAlguienAccess().getGroup()); }
)

;
finally {
	restoreStackSize(stackSize);
}




rule__Saludo__Alternatives
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getSaludoAccess().getBienvenidaParserRuleCall_0()); }
	ruleBienvenida
{ after(grammarAccess.getSaludoAccess().getBienvenidaParserRuleCall_0()); }
)

    |(
{ before(grammarAccess.getSaludoAccess().getDespedidaParserRuleCall_1()); }
	ruleDespedida
{ after(grammarAccess.getSaludoAccess().getDespedidaParserRuleCall_1()); }
)

;
finally {
	restoreStackSize(stackSize);
}



rule__Model__Group__0
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__Model__Group__0__Impl
	rule__Model__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__0__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getModelAccess().getQuienesAssignment_0()); }
(rule__Model__QuienesAssignment_0)*
{ after(grammarAccess.getModelAccess().getQuienesAssignment_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__Model__Group__1
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__Model__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__1__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getModelAccess().getSaludosAssignment_1()); }
(rule__Model__SaludosAssignment_1)*
{ after(grammarAccess.getModelAccess().getSaludosAssignment_1()); }
)

;
finally {
	restoreStackSize(stackSize);
}






rule__Bienvenida__Group__0
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__Bienvenida__Group__0__Impl
	rule__Bienvenida__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Bienvenida__Group__0__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getBienvenidaAccess().getHolaKeyword_0()); }

	'Hola' 

{ after(grammarAccess.getBienvenidaAccess().getHolaKeyword_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__Bienvenida__Group__1
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__Bienvenida__Group__1__Impl
	rule__Bienvenida__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Bienvenida__Group__1__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getBienvenidaAccess().getAQuienAssignment_1()); }
(rule__Bienvenida__AQuienAssignment_1)
{ after(grammarAccess.getBienvenidaAccess().getAQuienAssignment_1()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__Bienvenida__Group__2
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__Bienvenida__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Bienvenida__Group__2__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getBienvenidaAccess().getExclamationMarkKeyword_2()); }

	'!' 

{ after(grammarAccess.getBienvenidaAccess().getExclamationMarkKeyword_2()); }
)

;
finally {
	restoreStackSize(stackSize);
}








rule__Despedida__Group__0
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__Despedida__Group__0__Impl
	rule__Despedida__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Despedida__Group__0__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getDespedidaAccess().getChauKeyword_0()); }

	'Chau' 

{ after(grammarAccess.getDespedidaAccess().getChauKeyword_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__Despedida__Group__1
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__Despedida__Group__1__Impl
	rule__Despedida__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Despedida__Group__1__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getDespedidaAccess().getAQuienAssignment_1()); }
(rule__Despedida__AQuienAssignment_1)
{ after(grammarAccess.getDespedidaAccess().getAQuienAssignment_1()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__Despedida__Group__2
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__Despedida__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Despedida__Group__2__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getDespedidaAccess().getExclamationMarkKeyword_2()); }

	'!' 

{ after(grammarAccess.getDespedidaAccess().getExclamationMarkKeyword_2()); }
)

;
finally {
	restoreStackSize(stackSize);
}








rule__Alguien__Group__0
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__Alguien__Group__0__Impl
	rule__Alguien__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Alguien__Group__0__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getAlguienAccess().getQuienKeyword_0()); }

	'quien' 

{ after(grammarAccess.getAlguienAccess().getQuienKeyword_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__Alguien__Group__1
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__Alguien__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Alguien__Group__1__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getAlguienAccess().getNameAssignment_1()); }
(rule__Alguien__NameAssignment_1)
{ after(grammarAccess.getAlguienAccess().getNameAssignment_1()); }
)

;
finally {
	restoreStackSize(stackSize);
}







rule__Model__QuienesAssignment_0
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getModelAccess().getQuienesAlguienParserRuleCall_0_0()); }
	ruleAlguien{ after(grammarAccess.getModelAccess().getQuienesAlguienParserRuleCall_0_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}

rule__Model__SaludosAssignment_1
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getModelAccess().getSaludosSaludoParserRuleCall_1_0()); }
	ruleSaludo{ after(grammarAccess.getModelAccess().getSaludosSaludoParserRuleCall_1_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}

rule__Bienvenida__AQuienAssignment_1
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getBienvenidaAccess().getAQuienAlguienCrossReference_1_0()); }
(
{ before(grammarAccess.getBienvenidaAccess().getAQuienAlguienIDTerminalRuleCall_1_0_1()); }
	RULE_ID{ after(grammarAccess.getBienvenidaAccess().getAQuienAlguienIDTerminalRuleCall_1_0_1()); }
)
{ after(grammarAccess.getBienvenidaAccess().getAQuienAlguienCrossReference_1_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}

rule__Despedida__AQuienAssignment_1
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getDespedidaAccess().getAQuienAlguienCrossReference_1_0()); }
(
{ before(grammarAccess.getDespedidaAccess().getAQuienAlguienIDTerminalRuleCall_1_0_1()); }
	RULE_ID{ after(grammarAccess.getDespedidaAccess().getAQuienAlguienIDTerminalRuleCall_1_0_1()); }
)
{ after(grammarAccess.getDespedidaAccess().getAQuienAlguienCrossReference_1_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}

rule__Alguien__NameAssignment_1
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getAlguienAccess().getNameIDTerminalRuleCall_1_0()); }
	RULE_ID{ after(grammarAccess.getAlguienAccess().getNameIDTerminalRuleCall_1_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}


RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' ('b'|'t'|'n'|'f'|'r'|'u'|'"'|'\''|'\\')|~(('\\'|'"')))* '"'|'\'' ('\\' ('b'|'t'|'n'|'f'|'r'|'u'|'"'|'\''|'\\')|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;


