/*
* generated by Xtext
*/
package org.uqbar.paco.dsl.xtext.saludos;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SaludosDSLStandaloneSetup extends SaludosDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new SaludosDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

