/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui.labeling;

import org.eclipse.xtext.xbase.ui.labeling.XbaseDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class MyDslDescriptionLabelProvider extends XbaseDescriptionLabelProvider {
}
