/*
 * generated by Xtext
 */
package org.uqbar.paco.dsl.xtext.saludos;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SaludosDSLRuntimeModule extends org.uqbar.paco.dsl.xtext.saludos.AbstractSaludosDSLRuntimeModule {

}
