/*
* generated by Xtext
*/
package org.uqbar.paco.dsl.xtext.saludos.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.uqbar.paco.dsl.xtext.saludos.services.SaludosDSLGrammarAccess;

public class SaludosDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SaludosDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.uqbar.paco.dsl.xtext.saludos.parser.antlr.internal.InternalSaludosDSLParser createParser(XtextTokenStream stream) {
		return new org.uqbar.paco.dsl.xtext.saludos.parser.antlr.internal.InternalSaludosDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public SaludosDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SaludosDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
