/*
* generated by Xtext
*/
package org.uqbar.paco.dsl.xtext.saludos.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SaludosDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/uqbar/paco/dsl/xtext/saludos/parser/antlr/internal/InternalSaludosDSL.tokens");
	}
}
