/*
* generated by Xtext
*/
package org.uqbar.paco.dsl.xtext.saludos.ui.labeling

import com.google.inject.Inject
import org.uqbar.paco.dsl.xtext.saludos.saludosDSL.Saludo
import org.uqbar.paco.dsl.xtext.saludos.saludosDSL.Alguien
import org.uqbar.paco.dsl.xtext.saludos.saludosDSL.Model

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
class SaludosDSLLabelProvider extends org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider {

	@Inject
	new(org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
	
	// Model
	def image(Model model) {
		'saludo.jpg'
	}
	
	// Saludo
	def text(Saludo saludo) {
		'Un saludo a ' + saludo.AQuien.name 
	}
	def image(Saludo saludo) {
		'saludo.jpg'
	}
	
	// Alguien
	def image(Alguien alguien) {
		'alguien.png'
	}
}
