/*
 * generated by Xtext
 */
package org.uqbar.paco.dsl.xtext.saludos.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SaludosDSLUiModule extends org.uqbar.paco.dsl.xtext.saludos.ui.AbstractSaludosDSLUiModule {
	public SaludosDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
