/*
* generated by Xtext
*/
package org.uqbar.paco.dsl.xtext.saludos.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.uqbar.paco.dsl.xtext.saludos.services.SaludosDSLGrammarAccess;

public class SaludosDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private SaludosDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.uqbar.paco.dsl.xtext.saludos.ui.contentassist.antlr.internal.InternalSaludosDSLParser createParser() {
		org.uqbar.paco.dsl.xtext.saludos.ui.contentassist.antlr.internal.InternalSaludosDSLParser result = new org.uqbar.paco.dsl.xtext.saludos.ui.contentassist.antlr.internal.InternalSaludosDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSaludoAccess().getAlternatives(), "rule__Saludo__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getBienvenidaAccess().getGroup(), "rule__Bienvenida__Group__0");
					put(grammarAccess.getDespedidaAccess().getGroup(), "rule__Despedida__Group__0");
					put(grammarAccess.getAlguienAccess().getGroup(), "rule__Alguien__Group__0");
					put(grammarAccess.getModelAccess().getQuienesAssignment_0(), "rule__Model__QuienesAssignment_0");
					put(grammarAccess.getModelAccess().getSaludosAssignment_1(), "rule__Model__SaludosAssignment_1");
					put(grammarAccess.getBienvenidaAccess().getAQuienAssignment_1(), "rule__Bienvenida__AQuienAssignment_1");
					put(grammarAccess.getDespedidaAccess().getAQuienAssignment_1(), "rule__Despedida__AQuienAssignment_1");
					put(grammarAccess.getAlguienAccess().getNameAssignment_1(), "rule__Alguien__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.uqbar.paco.dsl.xtext.saludos.ui.contentassist.antlr.internal.InternalSaludosDSLParser typedParser = (org.uqbar.paco.dsl.xtext.saludos.ui.contentassist.antlr.internal.InternalSaludosDSLParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SaludosDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SaludosDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
