/*
* generated by Xtext
*/
grammar InternalSaludosDSL;

options {
	superClass=AbstractInternalAntlrParser;
	
}

@lexer::header {
package org.uqbar.paco.dsl.xtext.saludos.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package org.uqbar.paco.dsl.xtext.saludos.parser.antlr.internal; 

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import org.uqbar.paco.dsl.xtext.saludos.services.SaludosDSLGrammarAccess;

}

@parser::members {

 	private SaludosDSLGrammarAccess grammarAccess;
 	
    public InternalSaludosDSLParser(TokenStream input, SaludosDSLGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }
    
    @Override
    protected String getFirstRuleName() {
    	return "Model";	
   	}
   	
   	@Override
   	protected SaludosDSLGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}
}

@rulecatch { 
    catch (RecognitionException re) { 
        recover(input,re); 
        appendSkippedTokens();
    } 
}




// Entry rule entryRuleModel
entryRuleModel returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getModelRule()); }
	 iv_ruleModel=ruleModel 
	 { $current=$iv_ruleModel.current; } 
	 EOF 
;

// Rule Model
ruleModel returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
((
(
		{ 
	        newCompositeNode(grammarAccess.getModelAccess().getQuienesAlguienParserRuleCall_0_0()); 
	    }
		lv_quienes_0_0=ruleAlguien		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelRule());
	        }
       		add(
       			$current, 
       			"quienes",
        		lv_quienes_0_0, 
        		"Alguien");
	        afterParserOrEnumRuleCall();
	    }

)
)*(
(
		{ 
	        newCompositeNode(grammarAccess.getModelAccess().getSaludosSaludoParserRuleCall_1_0()); 
	    }
		lv_saludos_1_0=ruleSaludo		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelRule());
	        }
       		add(
       			$current, 
       			"saludos",
        		lv_saludos_1_0, 
        		"Saludo");
	        afterParserOrEnumRuleCall();
	    }

)
)*)
;





// Entry rule entryRuleSaludo
entryRuleSaludo returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getSaludoRule()); }
	 iv_ruleSaludo=ruleSaludo 
	 { $current=$iv_ruleSaludo.current; } 
	 EOF 
;

// Rule Saludo
ruleSaludo returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(
    { 
        newCompositeNode(grammarAccess.getSaludoAccess().getBienvenidaParserRuleCall_0()); 
    }
    this_Bienvenida_0=ruleBienvenida
    { 
        $current = $this_Bienvenida_0.current; 
        afterParserOrEnumRuleCall();
    }

    |
    { 
        newCompositeNode(grammarAccess.getSaludoAccess().getDespedidaParserRuleCall_1()); 
    }
    this_Despedida_1=ruleDespedida
    { 
        $current = $this_Despedida_1.current; 
        afterParserOrEnumRuleCall();
    }
)
;





// Entry rule entryRuleBienvenida
entryRuleBienvenida returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getBienvenidaRule()); }
	 iv_ruleBienvenida=ruleBienvenida 
	 { $current=$iv_ruleBienvenida.current; } 
	 EOF 
;

// Rule Bienvenida
ruleBienvenida returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='Hola' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getBienvenidaAccess().getHolaKeyword_0());
    }
(
(
		{
			if ($current==null) {
	            $current = createModelElement(grammarAccess.getBienvenidaRule());
	        }
        }
	otherlv_1=RULE_ID
	{
		newLeafNode(otherlv_1, grammarAccess.getBienvenidaAccess().getAQuienAlguienCrossReference_1_0()); 
	}

)
)	otherlv_2='!' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getBienvenidaAccess().getExclamationMarkKeyword_2());
    }
)
;





// Entry rule entryRuleDespedida
entryRuleDespedida returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getDespedidaRule()); }
	 iv_ruleDespedida=ruleDespedida 
	 { $current=$iv_ruleDespedida.current; } 
	 EOF 
;

// Rule Despedida
ruleDespedida returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='Chau' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getDespedidaAccess().getChauKeyword_0());
    }
(
(
		{
			if ($current==null) {
	            $current = createModelElement(grammarAccess.getDespedidaRule());
	        }
        }
	otherlv_1=RULE_ID
	{
		newLeafNode(otherlv_1, grammarAccess.getDespedidaAccess().getAQuienAlguienCrossReference_1_0()); 
	}

)
)	otherlv_2='!' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getDespedidaAccess().getExclamationMarkKeyword_2());
    }
)
;





// Entry rule entryRuleAlguien
entryRuleAlguien returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getAlguienRule()); }
	 iv_ruleAlguien=ruleAlguien 
	 { $current=$iv_ruleAlguien.current; } 
	 EOF 
;

// Rule Alguien
ruleAlguien returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='quien' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getAlguienAccess().getQuienKeyword_0());
    }
(
(
		lv_name_1_0=RULE_ID
		{
			newLeafNode(lv_name_1_0, grammarAccess.getAlguienAccess().getNameIDTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAlguienRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_1_0, 
        		"ID");
	    }

)
))
;





RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' ('b'|'t'|'n'|'f'|'r'|'u'|'"'|'\''|'\\')|~(('\\'|'"')))* '"'|'\'' ('\\' ('b'|'t'|'n'|'f'|'r'|'u'|'"'|'\''|'\\')|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;


